### PR TITLE
feat: Worksheet item actions (switch class' workspace), calendar additions and fixes

### LINKED ISSUE #1743: Calendar not user friendly on mobile
On mobile, the event boxes are too small, and when I first touch the box, it gets hovered and shows the buttons. The buttons are too easily clicked. We should only allow modifications via the sidebar on mobile (via [`(pointer: coarse)`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/pointer) detection), i.e. the buttons do not show on hover for mobile.

On a related note we should display the "edit" button in the sidebar. Makes me think that we should consolidate the three actions (edit, hide, remove) into a single "..." button with a dropdown. This is a part of https://github.com/coursetable/coursetable/issues/1784.

### PR DESCRIPTION
**Pull request by filippo-fonseca**
## Pre-flight checklist

- [x] I have searched for potential duplicate pull requests.
- [x] **If this is a code change**: I have written unit tests and/or conducted manual tests to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Summary

This PR fixes/implements the following **bugs/features**

- Calendar overflow issues on mobile are handled
- Worksheet actions are added (i.e. switch worksheet)
- Optimization of certain calendar elems)

## Test plan (required)

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

## Related issues/PRs

Fixes #1743, #1784

### CODE REVIEW

File: frontend/src/components/Worksheet/WorksheetCalendar.tsx [hunk 1]
```diff
@@ -21,30 +21,59 @@ function WorksheetCalendar() {
...
+        const otherStart = other.start.getTime();
+        const otherEnd = other.end.getTime();
+
+        if (
+          (otherStart >= start && otherStart < end) || // Overlaps in the middle
+          (start >= otherStart && start < otherEnd) // Starts within another event
+        ) 
+          count++;
+        
+      }
```
Comment (neilsong) [inline frontend/src/components/Worksheet/WorksheetCalendar.tsx:67]: Why do we warn when there are only more than 2 overlaps? Also an O(n^2) operation is expensive for just a warning (there was this one time some kid made a worksheet with like 5000 courses and we had to reset it in the db cuz frontend lag)

File: frontend/src/components/Worksheet/CalendarEvent.tsx [hunk 2]
```diff
@@ -13,9 +13,22 @@ const ResponsiveEllipsis = responsiveHOC()(LinesEllipsis);
...
+  const isMobile = useStore((state) => state.isMobile);
+
+  // This splits the title into separate lines for mobile!
+  const formattedTitle = isMobile
+    ? event.title.split(' ').map((word, index) => (
+        <React.Fragment key={index}>
+          {word}
+          {index < event.title.split(' ').length - 1 && <br />}
+        </React.Fragment>
+      ))
```
Comment (neilsong) [inline frontend/src/components/Worksheet/CalendarEvent.tsx:26]: How well does this work for very long titles?

File: frontend/src/components/Worksheet/WorksheetCalendar.tsx (hunk 1 above)
Comment (filippo-fonseca) [reply frontend/src/components/Worksheet/WorksheetCalendar.tsx:67]: oh this was just for testing, will remove!

File: frontend/src/components/Worksheet/CalendarEvent.tsx (hunk 2 above)
Comment (filippo-fonseca) [reply frontend/src/components/Worksheet/CalendarEvent.tsx:26]: Since it only happens on mobile (where we only show the course code), really well! Course codes are a very predictable format: EENG 200, for instance. Always a max four letter word and a number. *P.S. We don't show the full title on the mobile view now

**Comment by filippo-fonseca** [comment]
@neilsong anything I should fix before we get this merged?

**Review by neilsong — APPROVED** [review]
